name: Drive to YouTube Upload

on:
  schedule:
    - cron: '0 */12 * * *'  
  workflow_dispatch:        

jobs:
  upload:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Restore credential files
        run: |
          echo '${{ secrets.CLIENT_SECRET_JSON }}' > client_secret.json
          echo '${{ secrets.TOKEN_JSON }}' > token.json

      - name: Run upload script
        run: python main.py

      - name: Commit uploaded.json updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add uploaded.json
          git commit -m "update: uploaded.json after upload run" || echo "No changes to commit"
          git push
